- name: Сборка vpncore.aar через gomobile
        run: |
          export ANDROID_NDK_HOME=$ANDROID_HOME/ndk/25.2.9519653
          go install golang.org/x/mobile/cmd/gomobile@latest
          gomobile init

          mkdir -p android/app/libs
          cd native/vpncore
          go mod tidy
          gomobile bind -target=android -androidapi=26 -ldflags="-s -w" -o ../../android/app/libs/vpncore.aar .
